# Configuration for multiple pool support
[pools]

# Normal difficulty pool
[pools.normal]
host = "solo.ckpool.org"
port = 3333
user = "bc1q6f5zfvnl5yk0wfzv4gkgkfnmmjnzy72yc2y5v6.wk70"
pass = "anything123"
proxy_port = 3331

# High difficulty pool
[pools.high_diff]
host = "solo.ckpool.org"
port = 4334
user = "bc1q6f5zfvnl5yk0wfzv4gkgkfnmmjnzy72yc2y5v6.wk70"
pass = "anything123"
proxy_port = 3332
