services:
  proxy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: taohash-proxy
    volumes:
      - ../config:/app/config
    ports:
      - "${PROXY_PORT:-3331}:3331"
      - "${DASHBOARD_PORT:-5000}:5000"
      - "${RELOAD_API_PORT:-5001}:5001"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

networks:
  default:
    driver: bridge